# -*- coding: utf-8 -*-
"""Copy of CSE422 Lab Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135CoMY-2BlwTLY7rc6Nd7Cc9QQVfU9TG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.cluster import KMeans

df=pd.read_csv('/content/Dry_Bean.csv')
print("Dataset shape:",df.shape)
print("\nFirst 5 rows")
display(df.head())

"""# Dataset Description"""

print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nInfo:")
df.info()

print("\nClass Distribution:\n")
print(df["Class"].value_counts())


##Selecting numerical features
numerical_data = df.select_dtypes(include='number')

#append the features of numerical_data to list
numerical_features=numerical_data.columns.tolist()

print("\n")
print(f'There are {len(numerical_features)} numerical features:', '\n')
print(numerical_features)

#Selecting categoricalfeatures
categorical_data=df.select_dtypes(include= 'object')

#append the features of categorical_data to list
categorical_features=categorical_data.columns.tolist()
print("\n")
print(f'There are {len(categorical_features)} categorical features:', '\n')
print(categorical_features)

"""# Barplot of Distribution of DryBean Classes"""

plt.figure(figsize=(10,6))
sns.countplot(y='Class',data=df, palette='viridis')
plt.title('Distribution of Dry Bean Classes')
plt.xlabel('Count')
plt.ylabel("Bean class")
plt.show()

"""# Correlation Heatmap plot of whole dataset"""

plt.figure(figsize=(12,10))
corr_matrix=df.drop('Class',axis=1).corr()
sns.heatmap(corr_matrix,annot=False,cmap="coolwarm",linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

# Null / Missing Values
df.isnull().sum()


df.describe()

"""# Dataset Spliting(80% Trainset, 20% Test set)"""

X=df.drop('Class',axis=1)
y=df['Class']
label_encoder=LabelEncoder()
y_encoded=label_encoder.fit_transform(y)
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_scaled, y_encoded,test_size=0.2,random_state=42)
print("Training Data Shape", X_train.shape)
print("Testing Data Shape:" ,X_test.shape)

"""# Model Train and Confusion Matrix"""

models= {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100,random_state=42),
    "Suport Vector Machine": SVC(kernel='rbf', probability=True),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5)

}

results={}
for name, model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    results[name]=acc
    print(f"{name}")
    print(f"Accuracy: {acc:4f}")
    cm=confusion_matrix(y_test,y_pred)
    plt.figure(figsize=(6,4))
    sns.heatmap(cm,annot=True,fmt='d',cmap='Blues',xticklabels=label_encoder.classes_,yticklabels=label_encoder.classes_)
    plt.title(f'{name} Confusion Matrix')
    plt.ylabel('Actual')
    plt.xlabel("Predicted")
    plt.show()

"""# Neural Network"""

from sklearn.neural_network import MLPClassifier

nn_model = MLPClassifier(hidden_layer_sizes=(64,32), max_iter=1000, random_state=42)
nn_model.fit(X_train, y_train)
y_pred_nn = nn_model.predict(X_test)

acc_nn = accuracy_score(y_test, y_pred_nn)
print("Neural Network Accuracy:", acc_nn, "\n")


cm = confusion_matrix(y_test, y_pred_nn)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.title("Neural Network Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""# K-fold Cross Validation"""

print("\n 10 Fold Cross Validation")
kf=KFold(n_splits=10,shuffle=True,random_state=42)
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)

cv_scores=cross_val_score(rf_model,X_scaled,y_encoded,cv=kf,scoring='accuracy')
print(f"cross validation Accuracy score{cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard Deviation: {cv_scores.std():.4f}")

"""# Unsupervised Learning K means cluster"""

print("\n-- Unsupervised Learning K means cluster--")
wcss=[]
k_range=range(1,11)
for k in k_range:
    kmeans=KMeans(n_clusters=k,init='k-means++',max_iter=300, n_init=10,random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)
plt.figure(figsize=(8,5))
plt.plot(k_range,wcss,marker='o',linestyle='--',color='red')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Reduction in Variation (WCSS)')
plt.xticks(k_range)
plt.grid(True)
plt.show()

kmeans_final=KMeans(n_clusters=7,init='k-means++',random_state=42,n_init=10)
clusters=kmeans_final.fit_predict(X_scaled)
print('K-Means clustering completed')

"""# Accuracy Bar chart"""

import matplotlib.pyplot as plt

models = list(results.keys())
accuracies = list(results.values())

plt.figure(figsize=(8,5))
plt.bar(models, accuracies)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.xticks(rotation=45)
plt.show()

"""# Precision, Recall, F1-score"""

#Table format :
import pandas as pd
from sklearn.metrics import precision_score, recall_score

data = []

for name, model in models.items():
    y_pred = model.predict(X_test)

    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')

    data.append([name, precision, recall])

# Create table
df_metrics = pd.DataFrame(data, columns=["Model", "Precision", "Recall"])

print(df_metrics,"\n")


## Bar chart format :

import matplotlib.pyplot as plt
import numpy as np

x = np.arange(len(df_metrics["Model"]))

plt.figure(figsize=(8,5))
plt.bar(x - 0.2, df_metrics["Precision"], width=0.4, label='Precision')
plt.bar(x + 0.2, df_metrics["Recall"], width=0.4, label='Recall')

plt.xticks(x, df_metrics["Model"], rotation=45)
plt.ylabel("Score")
plt.title("Precision vs Recall Comparison")
plt.legend()

plt.show()

"""# AUC score, ROC curve for each model"""

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np

# number of classes
n_classes = len(np.unique(y_test))

# binarize labels
y_test_bin = label_binarize(y_test, classes=np.unique(y_test))

for name, model in models.items():

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)

        fpr = dict()
        tpr = dict()
        roc_auc = dict()

        plt.figure()

        for i in range(n_classes):
            fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
            roc_auc[i] = auc(fpr[i], tpr[i])

            plt.plot(fpr[i], tpr[i], label=f"Class {i} AUC={roc_auc[i]:.2f}")

        plt.plot([0,1],[0,1],'--')
        plt.title(name + " ROC Curve (Multiclass)")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.legend()

        plt.show()

"""# AUC Score

"""

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import label_binarize
import numpy as np

# binarize labels
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

for name, model in models.items():

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)

        auc_score = roc_auc_score(y_test_bin, y_prob, multi_class='ovr')

        print(name, "AUC:", auc_score)

    else:
        print(name, "AUC: Not available")