# -*- coding: utf-8 -*-
"""CSE422 Lab Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwTIvnx4MYRlyGxvpofRgntO8-Jn2IEo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.cluster import KMeans

df=pd.read_csv('/content/Dry_Bean.csv')
print("Dataset shape:",df.shape)
print("\nFirst 5 rows")
display(df.head())

plt.figure(figsize=(10,6))
sns.countplot(y='Class',data=df, palette='viridis')
plt.title('Distribution of Dry Bean Classes')
plt.xlabel('Count')
plt.ylabel("Bean class")
plt.show()

plt.figure(figsize=(12,10))
corr_matrix=df.drop('Class',axis=1).corr()
sns.heatmap(corr_matrix,annot=False,cmap="coolwarm",linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

X=df.drop('Class',axis=1)
y=df['Class']
label_encoder=LabelEncoder()
y_encoeded=label_encoder.fit_transform(y)
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_scaled, y_encoeded,test_size=0.2,random_state=42)
print("Training Data Shape", X_train.shape)
print("Testing Data Shape:" ,X_test.shape)

models= {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100,random_state=42),
    "Suport Vector Machine": SVC(kernel='rbf'),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Neural Network (MLP)": MLPClassifier(hidden_layer_sizes=(100,50),max_iter=500,random_state=42)

}

results={}
for name, model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    results[name]=acc
    print(f"{name}")
    print(f"Accuracy: {acc:4f}")
    cm=confusion_matrix(y_test,y_pred)
    plt.figure(figsize=(6,4))
    sns.heatmap(cm,annot=True,fmt='d',cmap='Blues',xticklabels=label_encoder.classes_,yticklabels=label_encoder.classes_)
    plt.title(f'{name} Confusion Matrix')
    plt.ylabel('Actual')
    plt.xlabel("Predicted")
    plt.show()

print("\n 10 Fold Cross Validation")
kf=KFold(n_splits=10,shuffle=True,random_state=42)
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)

cv_scores=cross_val_score(rf_model,X_scaled,y_encoeded,cv=kf,scoring='accuracy')
print(f"cross validation Accuracy score{cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard Deviation: {cv_scores.std():.4f}")

print("\n-- Unsupervised Learning K means cluster--")
wcss=[]
k_range=range(1,11)
for k in k_range:
    kmeans=KMeans(n_clusters=k,init='k-means++',max_iter=300, n_init=10,random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)
plt.figure(figsize=(8,5))
plt.plot(k_range,wcss,marker='o',linestyle='--',color='red')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Reduction in Variation (WCSS)')
plt.xticks(k_range)
plt.grid(True)
plt.show()

kmeans_final=KMeans(n_clusters=7,init='k-means++',random_state=42,n_init=10)
clusters=kmeans_final.fit_predict(X_scaled)
print('K-Means clustering completed')